version: '3'
services:
  webservice:
    container_name: web
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - /Users/jony/volumes/nginx/html:/usr/share/nginx/html
      - /Users/jony/volumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /Users/jony/volumes/nginx/conf/conf.d:/etc/nginx/conf.d
      - /Users/jony/volumes/nginx/log:/var/log/nginx
    restart: always